[package]
name = "snake_game"
version = "0.1.0"
authors = ["Void <57257404+into-the-v0id@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.4"
